### ISSUE TITLE
Doesn't generate documentation

### ISSUE THREAD

**Issue by nateberkopec** [TeWu/krpc-rb#5]
```
nodachi:Desktop nateberkopec$ gem install krpc
Fetching: ruby_protobuf-0.4.11.gem (100%)
Successfully installed ruby_protobuf-0.4.11
Fetching: krpc-0.2.2.gem (100%)
Successfully installed krpc-0.2.2
Parsing documentation for ruby_protobuf-0.4.11
Installing ri documentation for ruby_protobuf-0.4.11
ERROR:  While executing gem ... (OptionParser::InvalidArgument)
    invalid argument: --format hanna
```

**Comment by nateberkopec** [comment]
Same with Ruby 2.2 and Ruby 2.3

**Comment by djungelorm** [comment]
I get the same on ruby 2.1. Commenting out that line from krpc.gemfile fixes it!?

**Comment by TeWu** [comment]
You can probably eliminate the error by instaling [hanna-nouveau](https://github.com/rdoc/hanna-nouveau) gem first:
`gem install hanna-nouveau`

I'll come up with permanent fix soon. I guess there is something wrong with dependencies definitions.

**Comment by TeWu** [comment]
I verified that the problem concerns documentation generation, and not gem installation. You can still use the gem despite the error during docs generation, and both of above workarounds work for me.
